# -*- coding: utf-8 -*-
"""ML_polynomial_regression_library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7IMkbDAIQTaVnA1H9JhFjpn2UvvKPoe
"""

# Importing the necessary libraries

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from google.colab import files

"""**Reading the data**"""

data = pd.read_csv('Mumbai_House_Price.csv')

data

"""**Dropping ID and Price(Target Variable) from data**"""

data_X = data.drop(['id', 'Price'],axis=1)

"""**Importing models and libraries for Polynomial regression**"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

"""**Target Variable - Price**"""

data_Y = data['Price']

"""**Spliting the data into train data(80%) and test data(20%)**"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data_X, data_Y, test_size = 0.2, random_state = 200)

"""**For degree = 2**"""

degree = 2
polyreg = make_pipeline(PolynomialFeatures(degree),LinearRegression())

polyreg.fit(X_train, Y_train)

print(polyreg.score(X_train, Y_train))
print(polyreg.score(X_test, Y_test))

"""**For degree = 3**"""

degree = 3
polyreg = make_pipeline(PolynomialFeatures(degree),LinearRegression())

polyreg.fit(X_train, Y_train)

print(polyreg.score(X_train, Y_train))
print(polyreg.score(X_test, Y_test))

"""**For degree = 4**"""

degree = 4
polyreg = make_pipeline(PolynomialFeatures(degree),LinearRegression())

polyreg.fit(X_train, Y_train)

print(polyreg.score(X_train, Y_train))
print(polyreg.score(X_test, Y_test))