# -*- coding: utf-8 -*-
"""Random_Forest_Library.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1cNQDfg4KzoLOsjVs1B0oM9aK55o_b2
"""

# Importing the libraries 

import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from google.colab import files

"""**Reading the data**"""

data = pd.read_csv('Mumbai_House_Price.csv')

data

"""**1. Dropping ID and Price(Target Variable) from Data 2. Target Variable - Price 3. Spliting the data into train data(80%) and test data(20%)**"""

data_X = data.drop(['id', 'Price'],axis=1)

data_Y = data['Price']

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data_X, data_Y, test_size = 0.2, random_state = 0)

"""**Random Forest Regression - 20 decision trees**"""

from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators = 20, random_state = 0)
regressor.fit(X_train, Y_train)

"""**Predicting price for test data**"""

Y_predict_test = regressor.predict(X_test)
Y_predict_test

from sklearn.metrics import r2_score
r2_score(Y_test, Y_predict_test)

Y_predict_train = regressor.predict(X_train)
r2_score(Y_train, Y_predict_train)